# Generated by Django 3.2 on 2021-06-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default="What's up", max_length=1000)),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(null=True)),
                ('event', models.DateTimeField(null=True)),
            ],
        ),
    ]
