# Generated by Django 3.2 on 2022-08-19 14:24

from django.db import migrations, models
import my_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='myimage', validators=[my_app.validators.validate_file_size]),
        ),
    ]
